### ISSUE TITLE
Missing Tutorial 10 in the Playlist

### ISSUE THREAD

**Issue by tanmalik786** [BaronVonPerko/WordpressTailwindTheme#1]
Hi,
Thanks for the wonderful tutorial, it looks like the Playlist is missing Tutorial 10, which is probably about
`Tutorial: Wordpress Theme with TailwindCSS and Underscores 010 - Post Page (Part 1)`

Cause that appears to be missing link as the 11th tutorial is about
`Tutorial: Wordpress Theme with TailwindCSS and Underscores 011 - Post Page (Part 2)`

Will appreciate if you can make that available as well
Thanks,

**Comment by BaronVonPerko** [comment]
Hi Tanveer,

Thanks for letting me know!  The video was available, but for some reason
not in the youtube playlist.  I've fixed the playlist, and you can view the
missing video here:

https://www.youtube.com/watch?v=OuvkSntRtc4

Enjoy!

Chris
